### PR TITLE
Enable support for "return-empty"

### PR DESCRIPTION
**Pull request by geoffoxholm**
This small change adds support to get empty cells in the cell range.

### CODE REVIEW

**Comment by magnetikonline** [comment]
Hello @Lafcadio - thanks for the PR.

I'll review this work and get it merged - when time allows!

  Pete

**Comment by magnetikonline** [comment]
@Lafcadio I'm curious to know - where did you find `return-empty` documented at the official Google API docs page? :)

**Comment by geoffoxholm** [comment]
@magnetikonline - It's hinted at all over the place, but I agree, it's kind of illusive. Here's a link:
https://developers.google.com/gdata/javadoc/com/google/gdata/client/spreadsheet/CellQuery

**Comment by magnetikonline** [comment]
Thanks @Lafcadio - champion, I'll add that to the README.md when I _finally_ get around to merging (sorry, been a busy time in life!).

  Pete

**Comment by geoffoxholm** [comment]
No worries, @magnetikonline, thanks for your consideration.

**Comment by adriweb** [comment]
Note @Lafcadio: There needs to be `$value = $cellRangeCriteriaList[$key];` right before line 171 of the proposed patch.

**Comment by magnetikonline** [comment]
Thank @adriweb - I'll take that into consideration.

**Comment by geoffoxholm** [comment]
Yeah, @adriweb is right. Whoops. Not sure how that happened. Thanks.

**Comment by magnetikonline** [comment]
Hey @geoffoxholm - _finally_ getting around to some of these.... have committed your fine work as part of  58773de.

**Pull request closed without merging**
